// Generate visitor object

// visitor template
// {
//     "_id": 1,
//     "VNom": "Decroix",
//     "VPrenom": "Sacha",
//     "VVille": "Paris",
//     "VAge": 10,
//     "VDateVisite": "2023-06-01"
//   }

const fs = require('fs');

const prenomsFrancais = [
    "Emma",
    "Léo",
    "Louise",
    "Louis",
    "Alice",
    "Gabriel",
    "Chloé",
    "Jules",
    "Léa",
    "Adam",
    "Lucas",
    "Manon",
    "Inès",
    "Hugo",
    "Jade",
    "Ethan",
    "Camille",
    "Anna",
    "Arthur",
    "Lina",
    "Raphaël",
    "Léonie",
    "Noah",
    "Zoé",
    "Nathan",
    "Sarah",
    "Mathis",
    "Clara",
    "Enzo",
    "Juliette",
    "Paul",
    "Mila",
    "Tom",
    "Agathe",
    "Liam",
    "Romane",
    "Nolan",
    "Eva",
    "Théo",
    "Adèle",
    "Gabin",
    "Lola",
    "Maël",
    "Julia",
    "Timéo",
    "Léonie",
    "Ethan",
    "Ambre",
    "Maxime",
    "Léonore",
    "Noé",
    "Anaïs",
    "Clément",
    "Célia",
    "Sacha",
    "Lou",
    "Baptiste",
    "Rose",
    "Axel",
    "Maëlys",
    "Valentin",
    "Lilou",
    "Eliott",
    "Anaëlle",
    "Naël",
    "Elise",
    "Alexandre",
    "Ava",
    "Théodore",
    "Lena",
    "Antoine",
    "Mélissa",
    "Victor",
    "Louison",
    "Gaspard",
    "Lilas",
    "Robin",
    "Mia",
    "Bastien",
    "Apolline",
    "Aaron",
    "Elena",
    "Eliott",
    "Eléonore",
    "Matéo",
    "Mélanie",
    "Noé",
    "Capucine",
    "Luca",
    "Clémence",
    "Mohamed",
    "Léonie",
    "Maël",
    "Éléonore",
    "Augustin",
    "Zélie",
    "Elias",
    "Iris",
    "Martin",
    "Candice",
    "Mathéo",
    "Liliane",
    "Rayan",
    "Victoria",
    "Noé",
    "Romane",
    "Thibault",
    "Cassandre",
    "Samuel",
    "Louane",
    "Lucas",
    "Mélina",
    "Thomas",
    "Eloïse",
    "Maxence",
    "Garance",
    "Émile",
    "Lucie",
    "Esteban",
    "Charlotte",
    "Lenny",
    "Coralie",
    "Axel",
    "Émilie",
    "Kylian",
    "Manon",
    "Oscar",
    "Anaïs",
    "Gaspard",
    "Léonie",
    "Olivier",
    "Noémie",
    "Noam",
    "Flore",
    "Marius",
    "Amélie",
    "Simon",
    "Eléa",
    "Hippolyte"
]

const nomsFamilleFrancais = [
    "Martin",
    "Bernard",
    "Dubois",
    "Thomas",
    "Robert",
    "Richard",
    "Petit",
    "Durand",
    "Leroy",
    "Moreau",
    "Simon",
    "Laurent",
    "Lefebvre",
    "Michel",
    "Garcia",
    "David",
    "Bertrand",
    "Roux",
    "Vincent",
    "Fournier",
    "Morel",
    "Girard",
    "Andre",
    "Lefevre",
    "Mercier",
    "Dupont",
    "Lambert",
    "Bonnet",
    "Francois",
    "Martinez",
    "Legrand",
    "Garnier",
    "Faure",
    "Rousseau",
    "Blanc",
    "Guerin",
    "Muller",
    "Henry",
    "Roussel",
    "Nicolas",
    "Perrin",
    "Morin",
    "Mathieu",
    "Clement",
    "Gauthier",
    "Dumont",
    "Lopez",
    "Fontaine",
    "Chevalier",
    "Robin",
    "Masson",
    "Sanchez",
    "Fernandez",
    "Noel",
    "Meunier",
    "Leclerc",
    "Dubois",
    "Bouchard",
    "Roy",
    "Marchand",
    "Marie",
    "Lemoine",
    "Lecomte",
    "Dufour",
    "Joly",
    "Giraud",
    "Dumas",
    "Dubreuil",
    "Barbier",
    "Cousin",
    "Bailly",
    "Caron",
    "Guyot",
    "Colin",
    "Fabre",
    "Blanchard",
    "Adam",
    "Paris",
    "Pierre",
    "Renard",
    "Rolland",
    "Aubert",
    "Poirier",
    "Leclercq",
    "Vidal",
    "Renaud",
    "Duval",
    "Leroux",
    "Jean",
    "Adam",
    "Langlois",
    "Guillaume",
    "Roger",
    "Gaillard",
    "Rivet",
    "Fabre",
    "Dupuy",
    "Marty",
    "Lefort",
    "Dupuis",
    "Jean",
    "Lacombe",
    "Pons",
    "Laroche",
    "Renault",
    "Charles",
    "Huet",
    "Guillot",
    "Dupuis",
    "Lecomte",
    "Lefebvre",
    "Meyer",
    "Perrot",
    "Leclerc",
    "Lebrun",
    "Merle",
    "Fischer",
    "Remy",
    "Guillou",
    "Arnaud",
    "Poulain",
    "Besson",
    "Jacquet",
    "Rousseau",
    "Besson",
    "Cousin",
    "Laporte",
    "Hamon",
    "Louis",
    "Pichon",
    "Bourgeois",
    "Picard",
    "Dumont",
    "Leveque",
    "Jacob",
    "Perez",
    "Lucas",
    "Millet",
    "Lefevre"
]

const villesFrancaises = [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Le Havre",
    "Cergy-Pontoise",
    "Saint-Étienne",
    "Toulon",
    "Angers",
    "Grenoble",
    "Dijon",
    "Nîmes",
    "Aix-en-Provence",
    "Saint-Quentin-en-Yvelines",
    "Brest",
    "Le Mans",
    "Amiens",
    "Tours",
    "Limoges",
    "Clermont-Ferrand",
    "Villeurbanne",
    "Besançon",
    "Orléans",
    "Metz",
    "Rouen",
    "Mulhouse",
    "Perpignan",
    "Caen",
    "Boulogne-Billancourt",
    "Nancy",
    "Argenteuil",
    "Saint-Denis",
    "Roubaix",
    "Tourcoing",
    "Nanterre",
    "Avignon",
    "Vitry-sur-Seine",
    "Créteil",
    "Dunkirk",
    "Poitiers",
    "Asnières-sur-Seine",
    "Courbevoie",
    "Versailles"
];

let visiteurs = [];
let id = 1;


for (let i = 0; i < 100000; i++) {
    visiteurs.push(genererVisiteur());
}
fs.appendFile('visiteurs.json', JSON.stringify(visiteurs, undefined, 2) + "\n", function(err) {
    if (err) throw err;
    console.log('Saved!');
});


function genererVisiteur() {
    function randomDate(start, end) {
        return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
    }

    function randomInt(min, max) {
        return Math.floor(Math.random() * (max - min + 1) + min);
    }

    return {
        _id: id++,
        "VNom": nomsFamilleFrancais[Math.floor(Math.random() * nomsFamilleFrancais.length)],
        "VPrenom": prenomsFrancais[Math.floor(Math.random() * prenomsFrancais.length)],
        "Ville": villesFrancaises[Math.floor(Math.random() * villesFrancaises.length)],
        "Vage": randomInt(10, 80),
        "VDateVisite": randomDate(new Date(2010, 0, 1), new Date())
    }
}